name: 01-world

on:workflow_dispatch

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Print a greeting
        run: echo "Hello Githup Actions!!!"

      - name: Print Multi
        run: |
          echo "This step runs several shell commands"
          echo "Today's runner is: $RUNNER_OS"
          echo "The Repo is      : $GITHUB_REPOSITORY"
